; Auto-generated. Do not edit!


(cl:in-package baxterkitchen-msg)


;//! \htmlinclude PickResult.msg.html

(cl:defclass <PickResult> (roslisp-msg-protocol:ros-message)
  ((done
    :reader done
    :initarg :done
    :type cl:integer
    :initform 0))
)

(cl:defclass PickResult (<PickResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name baxterkitchen-msg:<PickResult> is deprecated: use baxterkitchen-msg:PickResult instead.")))

(cl:ensure-generic-function 'done-val :lambda-list '(m))
(cl:defmethod done-val ((m <PickResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader baxterkitchen-msg:done-val is deprecated.  Use baxterkitchen-msg:done instead.")
  (done m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickResult>) ostream)
  "Serializes a message object of type '<PickResult>"
  (cl:let* ((signed (cl:slot-value msg 'done)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickResult>) istream)
  "Deserializes a message object of type '<PickResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'done) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickResult>)))
  "Returns string type for a message object of type '<PickResult>"
  "baxterkitchen/PickResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickResult)))
  "Returns string type for a message object of type 'PickResult"
  "baxterkitchen/PickResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickResult>)))
  "Returns md5sum for a message object of type '<PickResult>"
  "ea92b6ec19d35b290c8fa8873bcfdd14")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickResult)))
  "Returns md5sum for a message object of type 'PickResult"
  "ea92b6ec19d35b290c8fa8873bcfdd14")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickResult>)))
  "Returns full string definition for message of type '<PickResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 done~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickResult)))
  "Returns full string definition for message of type 'PickResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 done~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PickResult
    (cl:cons ':done (done msg))
))
