; Auto-generated. Do not edit!


(cl:in-package baxterkitchen-msg)


;//! \htmlinclude PickGoal.msg.html

(cl:defclass <PickGoal> (roslisp-msg-protocol:ros-message)
  ((p_x
    :reader p_x
    :initarg :p_x
    :type cl:float
    :initform 0.0)
   (p_y
    :reader p_y
    :initarg :p_y
    :type cl:float
    :initform 0.0)
   (p_z
    :reader p_z
    :initarg :p_z
    :type cl:float
    :initform 0.0))
)

(cl:defclass PickGoal (<PickGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PickGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PickGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name baxterkitchen-msg:<PickGoal> is deprecated: use baxterkitchen-msg:PickGoal instead.")))

(cl:ensure-generic-function 'p_x-val :lambda-list '(m))
(cl:defmethod p_x-val ((m <PickGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader baxterkitchen-msg:p_x-val is deprecated.  Use baxterkitchen-msg:p_x instead.")
  (p_x m))

(cl:ensure-generic-function 'p_y-val :lambda-list '(m))
(cl:defmethod p_y-val ((m <PickGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader baxterkitchen-msg:p_y-val is deprecated.  Use baxterkitchen-msg:p_y instead.")
  (p_y m))

(cl:ensure-generic-function 'p_z-val :lambda-list '(m))
(cl:defmethod p_z-val ((m <PickGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader baxterkitchen-msg:p_z-val is deprecated.  Use baxterkitchen-msg:p_z instead.")
  (p_z m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PickGoal>) ostream)
  "Serializes a message object of type '<PickGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'p_x))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'p_y))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'p_z))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PickGoal>) istream)
  "Deserializes a message object of type '<PickGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'p_x) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'p_y) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'p_z) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PickGoal>)))
  "Returns string type for a message object of type '<PickGoal>"
  "baxterkitchen/PickGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PickGoal)))
  "Returns string type for a message object of type 'PickGoal"
  "baxterkitchen/PickGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PickGoal>)))
  "Returns md5sum for a message object of type '<PickGoal>"
  "36648e5f80a68644ee089d750f829141")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PickGoal)))
  "Returns md5sum for a message object of type 'PickGoal"
  "36648e5f80a68644ee089d750f829141")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PickGoal>)))
  "Returns full string definition for message of type '<PickGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 p_x~%float32 p_y~%float32 p_z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PickGoal)))
  "Returns full string definition for message of type 'PickGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%float32 p_x~%float32 p_y~%float32 p_z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PickGoal>))
  (cl:+ 0
     4
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PickGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PickGoal
    (cl:cons ':p_x (p_x msg))
    (cl:cons ':p_y (p_y msg))
    (cl:cons ':p_z (p_z msg))
))
