// Generated by gencpp from file baxterkitchen/PickResult.msg
// DO NOT EDIT!


#ifndef BAXTERKITCHEN_MESSAGE_PICKRESULT_H
#define BAXTERKITCHEN_MESSAGE_PICKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baxterkitchen
{
template <class ContainerAllocator>
struct PickResult_
{
  typedef PickResult_<ContainerAllocator> Type;

  PickResult_()
    : done(0)  {
    }
  PickResult_(const ContainerAllocator& _alloc)
    : done(0)  {
  (void)_alloc;
    }



   typedef int32_t _done_type;
  _done_type done;




  typedef boost::shared_ptr< ::baxterkitchen::PickResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baxterkitchen::PickResult_<ContainerAllocator> const> ConstPtr;

}; // struct PickResult_

typedef ::baxterkitchen::PickResult_<std::allocator<void> > PickResult;

typedef boost::shared_ptr< ::baxterkitchen::PickResult > PickResultPtr;
typedef boost::shared_ptr< ::baxterkitchen::PickResult const> PickResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baxterkitchen::PickResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baxterkitchen::PickResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace baxterkitchen

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'baxterkitchen': ['/home/team15/ee206akitchen/devel/share/baxterkitchen/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::baxterkitchen::PickResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baxterkitchen::PickResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxterkitchen::PickResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baxterkitchen::PickResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxterkitchen::PickResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baxterkitchen::PickResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baxterkitchen::PickResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea92b6ec19d35b290c8fa8873bcfdd14";
  }

  static const char* value(const ::baxterkitchen::PickResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea92b6ec19d35b29ULL;
  static const uint64_t static_value2 = 0x0c8fa8873bcfdd14ULL;
};

template<class ContainerAllocator>
struct DataType< ::baxterkitchen::PickResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baxterkitchen/PickResult";
  }

  static const char* value(const ::baxterkitchen::PickResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baxterkitchen::PickResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32 done\n\
";
  }

  static const char* value(const ::baxterkitchen::PickResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baxterkitchen::PickResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baxterkitchen::PickResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baxterkitchen::PickResult_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<int32_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BAXTERKITCHEN_MESSAGE_PICKRESULT_H
